name: DevSecOps

on: [push]

jobs:
  sast_scan:
    name: Run Bandit Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.8

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit Scan
      run: bandit --confidence-level medium --severity-level medium -r . -f json -o bandit-report.json

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: bandit-findings
        path: bandit-report.json

  docker_scan:
    name: Run Docker Scout
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Docker
      uses: docker-practice/actions-setup-docker@master
      with:
        docker_version: "24.0" 

    - name: Build Docker Image
      run: docker build --build-arg SOCKET_API_KEY=${{ secrets.SOCKET_API_KEY }} -f Dockerfile -t myapp:latest .

    #- name: Run Docker Scout
     # run:  |  
       #     curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
        #    sh install-scout.sh
         #   echo ${{secrets.DOCKER_PASS}} | docker login -u $#{{secrets.DOCKER_USER}} --password-stdin
         #   docker scout quickview
          #  docker scout cves

    - name: Run Docker Scout
      uses: docker/scout-action@v1
      with:
        command:  quickview, cves
        dockerhub-user: ${{secrets.DOCKER_USER}}
        dockerhub-password: ${{secrets.DOCKER_PASS}}
        only-severities: critical, high







